In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5]) #([1,2,3,4,5]) elemanlarından oluşan bir array tanımlayın

array([1, 2, 3, 4, 5])

In [5]:
np.zeros([4,5]) #0'lardan oluşan 4 satırlı 5 sütunlu bir array oluşturun

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones([3,5])*7 #7'lerden oluşan 3 satırlı 5 sütunlu bir array oluşturun

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [14]:
n = np.arange(10,70,5)
#10'dan başlayarak 70'e kadar 5'er artan ir array oluşturun. arrange() fonksiyonunu
n

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [13]:
np.linspace(0,5,15)
#0 ile 5 arasında 15 tane aynı uzaklıkta elemanı olan bir array
#oluşturun.linspace() fonk .

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [12]:
np.random.randn(3,5)
#normal dağılımda 3 satır 5 sütunlu bir array oluşturun.random.randn() fonk 

array([[-1.18857182, -1.28048259,  1.18035783,  1.17731594,  0.69858009],
       [-0.14513777, -0.98106878, -0.7971527 ,  0.47387766, -1.68772517],
       [-1.49625731,  0.79002843,  1.15127454,  0.26071772,  1.28943215]])

In [15]:
#5 elemanlı birim matris oluşturun. eye() fonk
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
#0'dan 24'e kadar sayıların olduuğu bir array oluşturun ve 
#reshape() metodunu kullanarak 4 satır ve 6 sütunlu hale getirin.
np.arange(24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [17]:
#0 ile 1 arasında rastgele 10 sayıdan oluşan bir array 
#tanımlayıp en düşük ve en yüksek değerleri tespit edin
b = np.random.rand(10)
b

array([0.8784991 , 0.76847476, 0.20307892, 0.01101157, 0.42626475,
       0.58662299, 0.13682611, 0.24081438, 0.99946248, 0.50664309])

In [18]:
b.max()

0.9994624788857366

In [19]:
b.min()

0.011011565984542449

In [22]:
#rastgele 16 sayıdan oluşan 4 satır ve 4 sütunlu bir array oluşturun.
n=np.random.random(16).reshape(4,4)
n

array([[0.59453891, 0.04665166, 0.33244237, 0.71956881],
       [0.89263942, 0.97728276, 0.10810801, 0.6092082 ],
       [0.03620328, 0.58622744, 0.52384435, 0.52457613],
       [0.19512333, 0.87073127, 0.47041691, 0.48142512]])

In [24]:
#2.satırdaki tüm elemanları çekin 
n[1:2,:]

array([[0.89263942, 0.97728276, 0.10810801, 0.6092082 ]])

In [25]:
#4.satır 4.sütundaki sayıyı çekin 
n[3,3]

0.48142511609161986

In [26]:
#4.sütundaki bütün elemanları çekin
n[:,3:4]

array([[0.71956881],
       [0.6092082 ],
       [0.52457613],
       [0.48142512]])

In [27]:
#For döngüsünü kullanarak oluşturduğunuz 16 sayıdan oluşan
#arrayin sayılarını alt alta flat() metodu kullanarak yazdırın
for i in n.flat:
    print(i)

0.5945389052963891
0.04665165706192698
0.3324423672272273
0.7195688072021739
0.892639424504341
0.9772827621040233
0.10810801462873898
0.6092081960114506
0.036203284197292795
0.5862274437631783
0.5238443486669585
0.5245761300683562
0.19512333030085938
0.8707312715081064
0.4704169149126932
0.48142511609161986


In [30]:
#0 ile 1 arasında rastgele 4 sayıdan oluşan bir array oluşturun
#ve her sayıyı 5 ile çarpın
h=np.random.random(4)*5
h

array([4.33155571, 3.3967868 , 4.52241192, 4.94166793])

In [31]:
#oluşturduğumuz arrayin sayılarının toplamını bulun
h.sum()

17.192422357471994

In [32]:
#oluşturduğumuz arrayin sayılarının standart sapmasını bulun
h.std()

0.5652389507288346

In [33]:
#oluşturduğumuz arrayin sayılarının varyansını bulun
h.var()

0.3194950714210339