# Numpy Basics


# Neden Numpy


In [2]:
import numpy # import numpy

In [3]:
print(numpy.array([1,2,3])) # numpy array oluşturmak.

[1 2 3]


In [4]:
import numpy as np # numpy için alias

In [5]:
a = np.array([1,2,3]) # array oluşturmak ve değişkene atamak.

In [6]:
a

array([1, 2, 3])

In [7]:
b = np.array([[1,2,3],[4,5,6]]) # iki boyutlu dizi oluşturmak.

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape # b oluşturulan array'in boyutların ulaşmak.

(2, 3)

In [10]:
a.shape # a oluşturulan array'in boyutların ulaşmak.

(3,)

In [40]:
b.size

6

In [11]:
b.dtype # array'in veri tipi.

dtype('int32')

In [12]:
b.ndim # array'in boyutu

2

In [13]:
a.ndim # array'in boyutu

1

In [14]:
print(type(a)) #type'ı ekrana basmak.

<class 'numpy.ndarray'>


In [15]:
np.arange(10) # birden 10'a kadar array oluşturmak.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.random.randint(10, size = (3,2,2))

array([[[9, 7],
        [9, 7]],

       [[7, 2],
        [2, 5]],

       [[3, 5],
        [7, 9]]])

In [42]:
np.random.randint(10, size = (2,4,1))

array([[[5],
        [4],
        [9],
        [5]],

       [[2],
        [7],
        [7],
        [7]]])

In [43]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [44]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

# Numpy Array Oluştrma

In [16]:
np.arange(2,12) #2'den 11' e kadar array oluşturma.

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.arange(2,12,2) #2'den 10'a kadar 2'şer artarak array oluşturma.

array([ 2,  4,  6,  8, 10])

In [18]:
np.zeros((3,2)) # 3x2 sıfır matrisi oluşturmak.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.ones((3,2)) # 3x2 bir matrisi oluşturmak.

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
np.eye(3) # 3x3 diagonal matris oluşturmak.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.full((3,3),2) # 3x3 2'ler matrisi oluşturma.

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [23]:
np.full((3,3),2.2, dtype= np.int) #float geçsek bile dtype int ise int matris oluşur.

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [24]:
np.full((3,3),2.2, dtype= np.float)

array([[2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2]])

In [25]:
np.diag([1,2,3,4,5]) # diagonal matrix.

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [26]:
v = np.array([1,2,3])
np.tile(v,(3,1)) # 3x3 aynı satırlardan oluşan matris.

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
v = np.array([1,2,3])
np.tile(v,(3,2)) # 3x3 aynı satırlardan oluşan matris.

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [28]:
# 0 ile 1 arası
np.random.random()

0.5413537151801739

In [29]:
# 2 ile 50 arası rassal sayı çekmek.
50*np.random.random()+2

42.60468260289628

In [30]:
np.random.random([3,3]) # 3'e 3 rassal sayı matrisi oluşturmak.

array([[0.0103546 , 0.650977  , 0.21347141],
       [0.30548328, 0.79165012, 0.63326272],
       [0.94997545, 0.90755095, 0.37464134]])

In [31]:
# 1 ile 50 arasında 100 rassal sayı oluşturmak.
a = np.linspace(1,50,100)

In [32]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [33]:
np.arange(24) # 0-23'e kadar sayı dizisi oluşturmak.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
np.arange(18).reshape(2,3,3)# ilk 18 sayıyı 3x3 2 adet matrise dağıtmak.

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

# Numpy dizi elemanlarına ulaşmak.

In [35]:
a = np.array([2,4,6,8,10,12,14,16])

In [36]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [37]:
a[2] # ikinci elemanı çağırmak

6

In [38]:
a[[2,4,6]] # 2,4 ve 6 index'li elemanları çağırmak.

array([ 6, 10, 14])

In [39]:
a[2:] # 2'den sonraki elemanları çağırmak.

array([ 6,  8, 10, 12, 14, 16])

In [45]:
a[2:5] # 2'den 5'e kadar elemanları çağırmak.

array([ 6,  8, 10])

In [46]:
a[0::2] # 0'dan 2 şer 2 şer index arttırarak elemanları çağırmak.

array([ 2,  6, 10, 14])

Lets check the same for 2 D array

In [47]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [48]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a[2,2] # 2 indexli matrisin 2 index'li elemanı.

9

In [50]:
a > 2 #hangi sayıların 2'den büyük olduğunu logical dönen ifade.

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [51]:
a[a > 2] # eğer 2'den büyük rakamları dönmek istersek.

array([3, 4, 5, 6, 7, 8, 9])

In [52]:
a[(a > 2) & (a < 5)] # kısıtlara uygun

array([3, 4])

# array subset'lemek

In [53]:
a = np.arange(10) # array oluşturmak.

In [54]:
b = a # array'i başka bir değişkene atamak.

In [55]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b[0] = 11 # array'deki bir değeri değiştirmek.

In [57]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

# Daha fazla

In [58]:
a = np.array([[1,2,3],[4,5,6]]) # 2x3 matris

In [59]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
a.T # matris transpoze

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
b = np.array([[7,8,9],[10,11,12]])

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [64]:
a == b # iki matrisin eşitliğinin logical kontrolü.

array([[False, False, False],
       [False, False, False]])

# Matematiksel Operasyonlar

In [65]:
a = np.arange(1,10)

In [66]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.sin(a) # bir array'deki tüm elemanların sinüsü

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [68]:
np.exp(a) # bir array'deki tüm elemanların sinüsü

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [69]:
np.sum(a) # bir arrayin toplamı.

45

In [70]:
np.median(a) # bir array'in medianı.

5.0

In [71]:
a.std() # bir array'in standart sapması.

2.581988897471611

In [72]:
a = np.arange(1,10).reshape(3,3) # 3'e 3 matris oluşturmak.

In [73]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
np.linalg.det(a) # determinantını almak.

-9.51619735392994e-16

In [75]:
np.linalg.inv(a) # bir matrisin tersini almak.

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [76]:
b = np.arange(11,20).reshape(3,3)

In [77]:
np.dot(a,b) # iki matrisin çarpımı

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [78]:
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)

In [79]:
a.sum() # bir matrisin toplamı.

2

In [80]:
a.max() # bir matrisin maksimum değeri..

True